// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var highlighter, updateConsole;
    highlighter = new RecursiveHighlighter('#highlight-target');
    updateConsole = function() {
      var endOffset, startOffset, _ref;
      $('#highlight-present').text(highlighter.selectionExists() ? 'yes' : 'no');
      $('#highlight-contained').text(highlighter.containsSelection() ? 'yes' : 'no');
      _ref = highlighter.getRelativeSelectionBounds(), startOffset = _ref[0], endOffset = _ref[1];
      $('#highlight-start').text(startOffset);
      return $('#highlight-end').text(endOffset);
    };
    $(document).on('mousemove', updateConsole);
    $(document).on('keypress', updateConsole);
    $(document).on('click', updateConsole);
    return $(document).on('click', '#mark-highlight', function() {
      if (highlighter.containsSelection()) {
        return highlighter.markHighlight(highlighter.getRelativeSelectionBounds());
      }
    });
  });

}).call(this);
